# Site settings
title: Alyssa's Coding Adventures
header-img: img/home-bg.png
email: alyssa.kim@gmail.com
copyright_name: alyssa0528
description: > # this means to ignore newlines until "baseurl:"
  My Software Development Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alyssa0528
learn_profile: alyssa0528
email_username: alyssa.kim@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
